<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>SelectiveVpnRouter.App</RootNamespace>
    <ApplicationIcon />
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SelectiveVpnRouter.Core\SelectiveVpnRouter.Core.csproj" />
  </ItemGroup>
</Project>
