<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(WindowsTargetFramework)</TargetFramework>
    <RootNamespace>SelectiveVpnRouter.Proxy</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SelectiveVpnRouter.Core\SelectiveVpnRouter.Core.csproj" />
    <ProjectReference Include="..\SelectiveVpnRouter.Network\SelectiveVpnRouter.Network.csproj" />
  </ItemGroup>
</Project>
